### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by zakiaziz** [kappataumu/letsencrypt-cloudflare-hook#13]
I have Python 2.7.6 running on a (somewhat) fresh install of ubuntu 14.04

```
$ ./letsencrypt.sh -c -d mydomain.com -t dns-01 -k 'hooks/cloudflare/hook.py'
#
# !! WARNING !! No main config file found, using default config!
#
+ Generating account key...
+ Registering account key with letsencrypt...
Processing mydomain.com
 + Signing domains...
 + Creating new directory /home/user/letsencrypt.sh/certs/mydomain.com ...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for mydomain.com...
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 14, in <module>
    import dns.resolver
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax
```

These are the steps I took before this error occurred:

```
$ git clone https://github.com/lukas2511/letsencrypt.sh
$ cd letsencrypt.sh
$ mkdir hooks
$ git clone https://github.com/kappataumu/letsencrypt-cloudflare-hook hooks/cloudflare
$ pip install -r hooks/cloudflare/requirements-python-2.txt
$ export CF_EMAIL='myemail@mydomain.com'
$ export CF_KEY='cloudflare_certificates_api_key'
```

**Comment by kappataumu** [comment]
Hello, can you run `pip list` and post the output?

**Comment by zakiaziz** [comment]
```
$ pip list
apt-xapian-index (0.45)
argparse (1.2.1)
awscli (1.10.0)
awsebcli (3.7.6)
backports.ssl-match-hostname (3.5.0.1)
blessed (1.9.5)
botocore (1.3.22)
cement (2.8.2)
chardet (2.0.1)
colorama (0.3.7)
configobj (4.7.2)
decorator (4.0.4)
dnspython3 (1.12.0)
docker-py (1.7.2)
dockerpty (0.4.1)
docopt (0.6.2)
docutils (0.12)
future (0.15.2)
GnuPGInterface (0.3.2)
gyp (0.1)
html5lib (0.999)
httplib2 (0.8)
iotop (0.6)
IPy (0.81)
jmespath (0.9.0)
keyring (3.5)
Landscape-Client (14.12)
launchpadlib (1.10.2)
lazr.restfulclient (0.13.3)
lazr.uri (1.0.3)
oauth (1.0.1)
PAM (0.4.2)
pathlib (1.0.1)
pathspec (0.3.4)
pip (1.5.4)
psutil (3.3.0)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pygobject (3.12.0)
pyOpenSSL (0.13)
pyserial (2.6)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 80, in run
    self.run_listing(options)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 142, in run_listing
    self.output_package_listing(installed_packages)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 151, in output_package_listing
    if dist_is_editable(dist):
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 366, in dist_is_editable
    req = FrozenRequirement.from_dist(dist, [])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 286, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError

Storing debug log for failure in /home/user/.pip/pip.log
```

**Comment by kappataumu** [comment]
You are getting that error because you have `dnspython3` installed (which is for Python 3), instead of `dnspython` (which is required for Python 2). 

Can you verify that you've actually installed the correct requirements, for Python 2?

**Comment by zakiaziz** [comment]
How can I do that?

I've ran `sudo pip install dnspython` and now `pip list` outputs:

```
$ pip list
apt-xapian-index (0.45)
argparse (1.2.1)
awscli (1.10.0)
awsebcli (3.7.6)
backports.ssl-match-hostname (3.5.0.1)
blessed (1.9.5)
botocore (1.3.22)
cement (2.8.2)
cffi (1.5.0)
chardet (2.0.1)
colorama (0.3.7)
configobj (4.7.2)
cryptography (1.2.3)
decorator (4.0.4)
dnspython (1.12.0)
dnspython3 (1.12.0)
docker-py (1.7.2)
dockerpty (0.4.1)
docopt (0.6.2)
docutils (0.12)
enum34 (1.1.2)
future (0.15.2)
GnuPGInterface (0.3.2)
gyp (0.1)
html5lib (0.999)
httplib2 (0.8)
idna (2.0)
iotop (0.6)
ipaddress (1.0.16)
IPy (0.81)
jmespath (0.9.0)
keyring (3.5)
Landscape-Client (14.12)
launchpadlib (1.10.2)
lazr.restfulclient (0.13.3)
lazr.uri (1.0.3)
ndg-httpsclient (0.4.0)
oauth (1.0.1)
PAM (0.4.2)
pathlib (1.0.1)
pathspec (0.3.4)
pip (1.5.4)
psutil (3.3.0)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
pygobject (3.12.0)
pyOpenSSL (0.15.1)
pyserial (2.6)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 80, in run
    self.run_listing(options)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 142, in run_listing
    self.output_package_listing(installed_packages)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 151, in output_package_listing
    if dist_is_editable(dist):
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 366, in dist_is_editable
    req = FrozenRequirement.from_dist(dist, [])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 286, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError

Storing debug log for failure in /home/user/.pip/pip.log
```

**Comment by zakiaziz** [comment]
Running `sudo pip install -r hooks/cloudflare/requirements-python-2.txt` now outputs:

```
$ sudo pip install -r hooks/cloudflare/requirements-python-2.txt
Requirement already satisfied (use --upgrade to upgrade): cffi==1.5.0 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): cryptography==1.2.3 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): dnspython==1.12.0 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): enum34==1.1.2 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): future==0.15.2 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): idna==2.0 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): ipaddress==1.0.16 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): ndg-httpsclient==0.4.0 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): pyasn1==0.1.9 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): pycparser==2.14 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL==0.15.1 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): requests==2.9.1 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): tld==0.7.6 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): wheel==0.28.0 in /usr/local/lib/python2.7/dist-packages (from -r hooks/cloudflare/requirements-python-2.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1.0 in /usr/local/lib/python2.7/dist-packages (from cryptography==1.2.3->-r hooks/cloudflare/requirements-python-2.txt (line 2))
Cleaning up...
```

**Comment by kappataumu** [comment]
Great, it seems you now have the packages you were missing in your previous `pip list`. Try running `pip uninstall dnspython3` and then executing `letsencrypt.sh` again. Post any errors.

**Comment by zakiaziz** [comment]
Actually after installing `dnspython` and running this:

```
$ ./letsencrypt.sh -c -d domain.com -t dns-01 -k 'hooks/cloudflare/hook.py'
```

Things seem to work. I did not uninstall `dnspython3`
