### ISSUE TITLE
On deploy_challenge "IndexError: list index out of range"

### ISSUE THREAD

**Issue by aijanai** [kappataumu/letsencrypt-cloudflare-hook#28]
When I try to renew a certificate, the following happens:

Processing vpn.staging-wanderio.com
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jan 10 15:19:00 2017 GMT (Less than 30 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for vpn.staging-wanderio.com...
 + CloudFlare hook executing: deploy_challenge
Traceback (most recent call last):
  File "cloudflare_hook/hook.py", line 196, in <module>
    main(sys.argv[1:])
  File "cloudflare_hook/hook.py", line 192, in main
    ops[argv[0]](argv[1:])
  File "cloudflare_hook/hook.py", line 165, in create_all_txt_records
    create_txt_record(args[i:i+X])
  File "cloudflare_hook/hook.py", line 103, in create_txt_record
    zone_id = _get_zone_id(domain)
  File "cloudflare_hook/hook.py", line 81, in _get_zone_id
    return r.json()['result'][0]['id']
IndexError: list index out of range

This has worked in the past, but all of a sudden in broke (a change in CF API?).

CF_EMAIL and CF_KEY are exported in the environment in which the script runs

**Comment by aijanai** [comment]
Ok, after manually replaying the request with PostMan I got it: the domain was actually not in CloudFlare, but still on Route53.
Maybe a more detailed error handling message would help.

**Comment by kappataumu** [comment]
Agreed, I'll push an update in the coming days.

**Comment by niieani** [comment]
Yup, encountered the same bug, was scratching my head for a better while.

**Comment by gwillem** [comment]
```
  File "hooks/cloudflare/hook.py", line 84, in _get_zone_id
    return r.json()['result'][0]['id']
IndexError: list index out of range
```
Same. Resulting json from CF is:
```
{
  "messages": [],
  "result_info": {
    "page": 1,
    "count": 0,
    "per_page": 20,
    "total_pages": 0,
    "total_count": 0
  },
  "errors": [],
  "success": true,
  "result": []
}
```

**Comment by aijanai** [comment]
Is this still an unaddressed issue @kappataumu ?

**Comment by 13223qweesadk** [comment]
Ran into this issue on Ubuntu 18.04.
Installing python 2 requirements resolved it for me even though the system uses python2 and 3 (and I think requirements.txt downgraded two python packages).

**Comment by thoraxe** [comment]
Appears to be related to #53

**Comment by thoraxe** [comment]
Looks like cloudflare deleted my site :(

**Comment by sonywork** [comment]
Because the get_tld changed:
  # tld = get_tld('http://' + domain)
    res = get_tld('http://' + domain, as_object=True)
    sub_domain, tld = res.subdomain, res.fld

**Comment by dynek** [comment]
I have the same problem and I confirm that what @kuleyang says is correct. It fixes the problem.
Thanks!

**Comment by YasharF** [comment]
Try https://github.com/SeattleDevs/letsencrypt-cloudflare-hook to see if that has resolved an issue.  That fork is actively maintained and PRs are welcome.

**Comment by rafiks** [comment]
> Try https://github.com/walcony/letsencrypt-cloudflare-hook to see if that has resolved an issue. That fork is actively maintained and PRs are welcome.

this other fork works for me
