### ISSUE TITLE
acme/new-authz returns [500] error

### ISSUE THREAD

**Issue by dr-dimitru** [kappataumu/letsencrypt-cloudflare-hook#36]
Hello,

Just faced this issue:
```plain
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-authz (Status 500)

Details:
<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An error occurred while processing your request.<p>
Reference&#32;&#35;179&#46;7941160&#46;1492661366&#46;abef6c5
</BODY></HTML>


 + CloudFlare hook executing: request_failure
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 203, in <module>
    main(sys.argv[1:])
  File "hooks/cloudflare/hook.py", line 199, in main
    ops[argv[0]](argv[1:])
KeyError: 'request_failure'
```

I'm using let's encrypt for long time, and recently decided to change validation method to DNS.
Thank you for great lib, hope we can solve it /

**Comment by dr-dimitru** [comment]
Solved by reinstalling pip packages with `--user` flag
