### ISSUE TITLE
KeyError: 'startup_hook'

### ISSUE THREAD

**Issue by westonmyers** [kappataumu/letsencrypt-cloudflare-hook#39]
The main [dehydrated project](https://github.com/lukas2511/dehydrated) was updated such that startup_hook needs to be defined within hooks to contain staging code, etc. As-is you receive the following when on the latest master of dehydrated.
```
 + CloudFlare hook executing: startup_hook
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 203, in <module>
     main(sys.argv[1:])
  File "hooks/cloudflare/hook.py", line 199, in main
    ops[argv[0]](argv[1:])
KeyError: 'startup_hook'
```

This is worked around by having the call defined, even if left empty, as such:

```
@@ -181,6 +181,8 @@ def delete_all_txt_records(args):
     for i in range(0, len(args), X):
         delete_txt_record(args[i:i+X])

+def startup_hook(args):
+    return

 def exit_hook(args):
     return
@@ -193,6 +195,7 @@ def main(argv):
         'deploy_cert'     : deploy_cert,
         'unchanged_cert'  : unchanged_cert,
         'invalid_challenge': invalid_challenge,
+        'startup_hook': startup_hook,
         'exit_hook': exit_hook
     }
     logger.info(" + CloudFlare hook executing: {0}".format(argv[0]))
```

You may want to shuffle around more things though.

**Comment by westonmyers** [comment]
Derp, meant for this to got into hook's issue. Sorry mate!

**Comment by westonmyers** [comment]
There's a PR for this, closing.
