### ISSUE TITLE
idna uninstalling

### ISSUE THREAD

**Issue by opyate** [kappataumu/letsencrypt-cloudflare-hook#44]
Hello, I'm using commit `a3c899d26e79cfa45e873dacbe85169cf84ea910` and running

    pip install -I -r hooks/cloudflare/requirements-python-2.txt

This is the output:

```
Cloning into 'hooks/cloudflare'...
Collecting cffi==1.5.0 (from -r hooks/cloudflare/requirements-python-2.txt (line 1))
  Downloading cffi-1.5.0.tar.gz (385kB)
Collecting cryptography==1.2.3 (from -r hooks/cloudflare/requirements-python-2.txt (line 2))
  Downloading cryptography-1.2.3.tar.gz (373kB)
Collecting dnspython==1.15.0 (from -r hooks/cloudflare/requirements-python-2.txt (line 3))
  Downloading dnspython-1.15.0-py2.py3-none-any.whl (177kB)
Collecting enum34==1.1.2 (from -r hooks/cloudflare/requirements-python-2.txt (line 4))
  Downloading enum34-1.1.2.tar.gz (46kB)
Collecting future==0.15.2 (from -r hooks/cloudflare/requirements-python-2.txt (line 5))
  Downloading future-0.15.2.tar.gz (1.6MB)
Collecting idna==2.0 (from -r hooks/cloudflare/requirements-python-2.txt (line 6))
  Downloading idna-2.0-py2.py3-none-any.whl (61kB)
Collecting ipaddress==1.0.16 (from -r hooks/cloudflare/requirements-python-2.txt (line 7))
  Downloading ipaddress-1.0.16-py27-none-any.whl
Collecting ndg-httpsclient==0.4.0 (from -r hooks/cloudflare/requirements-python-2.txt (line 8))
  Downloading ndg_httpsclient-0.4.0.tar.gz
Collecting pyasn1==0.1.9 (from -r hooks/cloudflare/requirements-python-2.txt (line 9))
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pycparser==2.14 (from -r hooks/cloudflare/requirements-python-2.txt (line 10))
  Downloading pycparser-2.14.tar.gz (223kB)
Collecting pyOpenSSL==0.15.1 (from -r hooks/cloudflare/requirements-python-2.txt (line 11))
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB)
Collecting requests==2.9.1 (from -r hooks/cloudflare/requirements-python-2.txt (line 12))
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
Collecting six==1.10.0 (from -r hooks/cloudflare/requirements-python-2.txt (line 13))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting tld==0.7.6 (from -r hooks/cloudflare/requirements-python-2.txt (line 14))
  Downloading tld-0.7.6-py2.py3-none-any.whl (147kB)
Collecting wheel==0.28.0 (from -r hooks/cloudflare/requirements-python-2.txt (line 15))
  Downloading wheel-0.28.0-py2.py3-none-any.whl (179kB)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1.0 in /usr/lib/python2.7/site-packages (from cryptography==1.2.3->-r hooks/cloudflare/requirements-python-2.txt (line 2))
Installing collected packages: pycparser, cffi, idna, pyasn1, six, enum34, ipaddress, cryptography, dnspython, future, pyOpenSSL, ndg-httpsclient, requests, tld, wheel
  Found existing installation: pycparser 2.18
    Uninstalling pycparser-2.18:
      Successfully uninstalled pycparser-2.18
  Running setup.py install for pycparser
  Found existing installation: cffi 1.11.0
    Uninstalling cffi-1.11.0:
      Successfully uninstalled cffi-1.11.0
  Running setup.py install for cffi
  Found existing installation: idna 2.6
    Uninstalling idna-2.6:
      Successfully uninstalled idna-2.6
  Rolling back uninstall of idna
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 242, in move_wheel_files
    name, user=user, home=home, root=root, isolated=isolated
  File "/usr/lib/python2.7/site-packages/pip/locations.py", line 181, in distutils_scheme
    d = Distribution(dist_args)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
    for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 732, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2458, in parse_map
    for group, lines in data:
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3089, in split_sections
    for line in yield_lines(s):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2313, in yield_lines
    for ss in strs:
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2653, in _get_metadata
    if self.has_metadata(name):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1629, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1987, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1867, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1807, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/idna-2.6-py2.7.egg'
```

So, even though `idna` is in the requirements, something is making it uninstall. Any pointers?

**Comment by opyate** [comment]
I made a Dockerfile here to recreate more easily: https://github.com/opyate/docker-letsencrypt-nginx-proxy-companion

**Comment by opyate** [comment]
I'll try the workaround here: zenhack/simp_le/issues/62

**Comment by opyate** [comment]
Said workaround [fixes my problem](https://github.com/opyate/docker-letsencrypt-nginx-proxy-companion/commit/03575552cb8f9b37900b6208e2cff51ef5ab898c). Closing.
