### ISSUE TITLE
Error after successful run

### ISSUE THREAD

**Issue by liquidox** [kappataumu/letsencrypt-cloudflare-hook#45]
I get this error at the end of a seemingly successful run.

` + CloudFlare hook executing: exit_hook
Traceback (most recent call last):
  File "/etc/dehydrated/hooks/cloudflare/hook.py", line 157, in <module>
    main(sys.argv[1:])
  File "/etc/dehydrated/hooks/cloudflare/hook.py", line 153, in main
    ops[argv[0]](argv[1:])
KeyError: 'exit_hook'
`

Am using:
`dehydrated.noarch                       0.4.0-5.el7              @epel`

**Comment by Asara** [comment]
I am having the same issue.

Dehydrated version: 0.6.0

**Comment by hakamairi** [comment]
Hit the same, using master dehydrated from 12.02 and same from cloudflare hook. Refetching both fixed the issue.

**Comment by kappataumu** [comment]
@liquidox @Asara @hakamairi Which Python version are you using?

**Comment by Asara** [comment]
@kappataumu Currently using 2.7.5 (default in Centos 7)

**Comment by kappataumu** [comment]
@Asara Thanks. Can you reproduce using the current `master`? Is the error consistently coming up?

**Comment by Asara** [comment]
@kappataumu Seem to be able to use master with no problems now!

Thanks buddy.
