### ISSUE TITLE
Cannot create a certificate for my domain / deploy_challenge crash

### ISSUE THREAD

**Issue by Anarethos** [kappataumu/letsencrypt-cloudflare-hook#53]
Hi!
We have two domain and we are unable to create certificates for one of them.

Domain 1 : montreal.ca
Domain 2: ville.montreal.qc.ca

I can create what I want for the "montreal.ca" domain. Like "test.montreal.ca", "test.api.montreal.ca", etc.

BUT I can't create any certificate for "ville.montreal.qc.ca". Entries like "test.ville.montreal.qc.ca" or "test.api.ville.montreal.qc.ca" cannot be made.

I gen the following error.

# INFO: Using main config file /etc/dehydrated/config
# INFO: Using additional config file /etc/dehydrated/conf.d/local.sh
 + CloudFlare hook executing: startup_hook
Processing kronos.ville.montreal.qc.ca
 + Creating new directory /etc/dehydrated/certs/kronos.ville.montreal.qc.ca ...
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for kronos.ville.montreal.qc.ca
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 + CloudFlare hook executing: deploy_challenge
 + Creating TXT record: kronos.ville.montreal.qc.ca => AvrujpuBA5Hpl681oDSae67EHHJ8DvNiHbuhThteW24
 + Challenge: mrM0VGPAwi3LO3nhr46j7p6aRZHmjlrlu4Kq9vS0AaI
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 206, in <module>
    main(sys.argv[1:])
  File "hooks/cloudflare/hook.py", line 203, in main
    ops[argv[0]](argv[1:])
  File "hooks/cloudflare/hook.py", line 167, in create_all_txt_records
    create_txt_record(args[i:i+X])
  File "hooks/cloudflare/hook.py", line 105, in create_txt_record
    zone_id = _get_zone_id(domain)
  File "hooks/cloudflare/hook.py", line 83, in _get_zone_id
    return r.json()['result'][0]['id']
IndexError: list index out of range
 + CloudFlare hook executing: exit_hook

Anyone can help ?

Thanks.

**Comment by chitoku-k** [comment]
Experiencing a somewhat similar issue here.

The Cloudflare API currently returns an empty list for the query that only consists of TLD. Changing `_get_zone_id` to send a request by `domain` seemed to solve the problem.

https://github.com/kappataumu/letsencrypt-cloudflare-hook/blob/e78005a554e9f9917403110ada6f09184f49314b/hook.py#L80

to something like:

```python
    url = "https://api.cloudflare.com/client/v4/zones?name={0}".format(domain) 
```

**Comment by thoraxe** [comment]
Similar error myself:

```
 + CloudFlare hook executing: deploy_challenge
Traceback (most recent call last):
  File "/opt/letsencrypt-cloudflare-hook/hook.py", line 206, in <module>
    main(sys.argv[1:])
  File "/opt/letsencrypt-cloudflare-hook/hook.py", line 203, in main
    ops[argv[0]](argv[1:])
  File "/opt/letsencrypt-cloudflare-hook/hook.py", line 167, in create_all_txt_records
    create_txt_record(args[i:i+X])
  File "/opt/letsencrypt-cloudflare-hook/hook.py", line 105, in create_txt_record
    zone_id = _get_zone_id(domain)
  File "/opt/letsencrypt-cloudflare-hook/hook.py", line 83, in _get_zone_id
    return r.json()['result'][0]['id']
IndexError: list index out of range
```

This is with a single domain that looks like `foo.bar.baz.com`

I tried the edit suggested by @chitoku-k but it did not solve the issue for me.

**Comment by thoraxe** [comment]
NVM my issue was apparently that Cloudflare had nuked my domain.
