### ISSUE TITLE
cloudflare/hook.py: No such file or directory

### ISSUE THREAD

**Issue by adrianoresende** [kappataumu/letsencrypt-cloudflare-hook#8]
```
#
# !! WARNING !! No main config file found, using default config!
#
Processing foo.com
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for foo.com...
./letsencrypt.sh: line 425: python ~/letsencrypt.sh/hooks/cloudflare/hook.py: No such file or directory

deploy@x:~/letsencrypt.sh$ python ~/letsencrypt.sh/hooks/cloudflare/hook.py 
 + Unable to locate Cloudflare credentials in environment!
```

Whats is problem?
PS: I changed URL to foo.com only this issue.

**Comment by kappataumu** [comment]
Hi! Can you show me the entire command line you are using?

**Comment by adrianoresende** [comment]
`./letsencrypt.sh -c -d hml.foo.com -t dns-01 -k 'python '~/letsencrypt.sh/hooks/cloudflare/hook.py'`

**Comment by kappataumu** [comment]
Ah, I guess you copied the usage from my blog? I should update that post. Try like so, and tell me if it works: 

`./letsencrypt.sh -c -d hml.foo.com -t dns-01 -k '~/letsencrypt.sh/hooks/cloudflare/hook.py'`

**Comment by adrianoresende** [comment]
Not work =/
How do more debug?

**Comment by adrianoresende** [comment]
Yeah! Is it work =D
But have other error:

```
#
# !! WARNING !! No main config file found, using default config!
#
Processing hml.foo.com.br
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for hml.foo.com...
 + CloudFlare hook executing: deploy_challenge
 + Settling down for 10s...
 + Responding to challenge for hml.foo.com.br...
 + CloudFlare hook executing: clean_challenge
 + Challenge is valid!
 + Requesting certificate...
 + Checking certificate...
 + Done!
 + Creating fullchain.pem...
 + CloudFlare hook executing: deploy_cert
Traceback (most recent call last):
  File "hooks/cloudflare/hook.py", line 154, in <module>
    main(sys.argv[1:])
  File "hooks/cloudflare/hook.py", line 150, in main
    ops[argv[0]](argv[1:])
  File "hooks/cloudflare/hook.py", line 137, in deploy_cert
    domain, privkey_pem, cert_pem, fullchain_pem, chain_pem = args
ValueError: too many values to unpack
```

**Comment by kappataumu** [comment]
Glad it worked. Regarding the error you are getting, I see that `letsencrypt.sh` has added a `timestamp` parameter to the `deploy_cert` hook that we are not currently handling. I'll push a fix.

Thanks for the bug report! :)

**Comment by pyther** [comment]
I submitted PR #10 which includes a fix for the new timestamp and add support for the `unchange_cert`.

**Comment by kappataumu** [comment]
That's awesome, merging.
